config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get '/portfolio' => 'pages#portfolio'
  get '/about' => 'pages#about'

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def portfolio
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500;700&display=swap" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="header">
  <div class="container">
     <ul class="nav">
      <li> <%= link_to "Welcome", root_path, class:"link" %></li>
      <li><%= link_to "Portfolio", portfolio_path, class:"link" %></li>
      <li><%= link_to "About ", about_path, class:"link" %></li>
      <li><a href="#bottom">Contact</a></li>
    </ul>
  </div>
</div>

<div class="img-grid-btn">
  <img src="https://lh3.googleusercontent.com/qq7VR4Pn__63-v8epApbXYy8LTj3z8CpmLTqS6CoXkI23gHv1kQubmdmtFi9lkmwif-C_w4zuZg1Xxvq1rOC86wvREAnTu75-uGlVRjLCMm45C7y-2MC8XyYYkzZRnqhpFE2oyPfYQ=w600-h315-p-k"/> <p>My name is Parisa and I am 34 years old. Since 2010, I have worked as civil engineer and I am interested to combine computer science into civil engineering to provide creative tools in construction industry. </p>
  </div>
<div class="main">


<div class="footer">
  <div class="container">
    <a href="https://www.linkedin.com/in/parisa-shekari-05ab8442/" target = "_blank"><img src="https://lh3.googleusercontent.com/mCf25Q6jgW6rDE269ipNGOq08tTA575uyfSclJsVGoZTytRueSSDZrvtrL2pWkQFwK3UZ7jhFo2Zkbqe7ULmJ7wngz6qAwXQxL72zJyyD1qisL7WjdsBBasDogF9jQveipNXMmA9VA=s256-p-k" /></a>
    <a id="bottom"><img src="https://lh3.googleusercontent.com/npJM4szIetyjVsRGJ-WtxN-0_qPnHmyactkmezo5gHFcBABvl-GKtRjVfqU4TkQJgY8EAKsOg5kJSJbRqdvFNGb8TAT8pKId5I9W3yOWXfrfOH8EVZb1Jc06kHSUprOCNjFvacu6Pg=s256-p-k" /><strong>parisa.shekari@gmail.com</strong></a>
  </div>
</div>

app/views/pages/portfolio.html.erb
<div class="header">
  <div class="container">
     <ul class="nav">
      <li> <%= link_to "Welcome", root_path, class:"link" %></li>
      <li><%= link_to "Portfolio", portfolio_path, class:"link" %></li>
      <li><%= link_to "About ", about_path, class:"link" %></li>
      <li><a href="#bottom">Contact</a></li>
    </ul>
  </div>
</div>
<div class="main">
  <div class="container">
  <img src="https://lh3.googleusercontent.com/Rmt_6VUZWdSopHjxZaknumawzvT-1uXfMYPlHOkLethipnNOY1MLUF33eYvflF74dxZHf1lVmwTveuVgBBe9-2IOS1-B4Ts-DigTNlggxa7LT2A8QDqJO1yC71hFKsB-w6lVzxqzOQ=w600-h315-p-k" />
  <br></br>
<div class="img-grid">
  <img src="https://lh3.googleusercontent.com/Vio-xmRboHk-IhHtsJshJcyefrjwdq_lmlE0dmZDxrLFXGgsffIPyUYB0rgalCUSwhF1vRWI-kWkVyL7icnjrtbZ3R2HpvlULPw44m3IAl3Ufo3mYwN20x8jOtcBMBeG3OrCLILXSw=w600-h315-p-k" />
 
  <img src="https://lh3.googleusercontent.com/PXOQKSTJWUwLi1sAi88uK3SuKMuQbL3U3mygKcZfghrASzZgDZyuNNNF19llqVbvlLv7Ctcx2v-1g7cDj2Gezk5R0vce0in0qfKwMWTCJZnw-C_hcZPGt3JuISbDZn9ZtA7vH_7qRA=w600-h315-p-k" />
</div>

<div class="description">
  
  <p><strong>Commercial Project</strong><br></br>I have been engaged in comprehensive design, engineering, procurement, construction and project management services for mass commercial projects.I analyze cost/benefit factors for various building systems to achieve maximum cost savings for our customers, without compromising quality.<a href="https://www.kayson-ir.com/divisions.aspx?topic=hous"> Learn more</a></p> 
  
  
  <p><strong>Railway Project</strong><br></br>The construction of railway systems is part of a irania nationally-coordinated plan to ease traffic congestion in major cities.I have been engaged in project management of the first phase of the project, which comprises a 6.8 km line with eight stations. The project was constructed in 5 years. To know more about this project: <a href="https://www.kayson-ir.com/project.aspx?topic=monorail&cat=rtrans"> Learn more</a> </p>
</div>

  
<div class="footer">
  <div class="container">
    <a href="https://www.linkedin.com/in/parisa-shekari-05ab8442/" target = "_blank"><img src="https://lh3.googleusercontent.com/mCf25Q6jgW6rDE269ipNGOq08tTA575uyfSclJsVGoZTytRueSSDZrvtrL2pWkQFwK3UZ7jhFo2Zkbqe7ULmJ7wngz6qAwXQxL72zJyyD1qisL7WjdsBBasDogF9jQveipNXMmA9VA=s256-p-k" /></a>
    <a id="bottom"><img src="https://lh3.googleusercontent.com/npJM4szIetyjVsRGJ-WtxN-0_qPnHmyactkmezo5gHFcBABvl-GKtRjVfqU4TkQJgY8EAKsOg5kJSJbRqdvFNGb8TAT8pKId5I9W3yOWXfrfOH8EVZb1Jc06kHSUprOCNjFvacu6Pg=s256-p-k" /><strong>parisa.shekari@gmail.com</strong></a>
  </div>
</div>

app/views/pages/welcome.html.erb
<div class="header">
  <div class="container">
     <ul class="nav">
      <li> Welcome </li><% link_to 'portfolio'%>
      <li><%= link_to "Portfolio", portfolio_path, class:"link" %></li>
      <li> About </li>
      <li> Contact </li>
    </ul>
  </div>
</div>
<div class="main">
  <div class="container">
  <a href="https://lh3.googleusercontent.com/RXPnea00jY6lG_WIAcsMz56DHqATVb3kqnIZsBdf3Fi96Q2RLHxDYUGak7zqrzhuDUSJY7lda4HFkDuPYmx8ECP96NILyiz2BVWvJli-c8EmcBecZNfOYHAkPRfjOAf802Vw59sVfw=w2400?source=screenshot.guru"> <img src="https://lh3.googleusercontent.com/RXPnea00jY6lG_WIAcsMz56DHqATVb3kqnIZsBdf3Fi96Q2RLHxDYUGak7zqrzhuDUSJY7lda4HFkDuPYmx8ECP96NILyiz2BVWvJli-c8EmcBecZNfOYHAkPRfjOAf802Vw59sVfw=w600-h315-p-k" /> </a>
    <h4>My name is Parisa, an experienced civil engineer interested in computer science. I am currently in Sydney, Australia for my PhD in Civil engineering.<h4> 
    <a class ="btn-primary" href="./portfolio.html">View my Portfolio</a>  
   <br></br>
   <br></br>
   <br></br>
  </div>

<div class="footer">
  <div class="container">
    <a href="https://www.linkedin.com/in/parisa-shekari-05ab8442/" target = "_blank"><img src="https://lh3.googleusercontent.com/mCf25Q6jgW6rDE269ipNGOq08tTA575uyfSclJsVGoZTytRueSSDZrvtrL2pWkQFwK3UZ7jhFo2Zkbqe7ULmJ7wngz6qAwXQxL72zJyyD1qisL7WjdsBBasDogF9jQveipNXMmA9VA=s256-p-k" /></a>
    <a><img src="https://lh3.googleusercontent.com/npJM4szIetyjVsRGJ-WtxN-0_qPnHmyactkmezo5gHFcBABvl-GKtRjVfqU4TkQJgY8EAKsOg5kJSJbRqdvFNGb8TAT8pKId5I9W3yOWXfrfOH8EVZb1Jc06kHSUprOCNjFvacu6Pg=s256-p-k" /><strong>parisa.shekari@gmail.com</strong></a>
  </div>
</div>